In [1]:
import pandas as pd
df= pd.read_csv("C:\\Users\\Hp\\Desktop\\Programs\\python_module_pandas\\src\\IMDB Top 250 Movies.csv")

In [2]:
df

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,The Help,2011,8.1,Drama,PG-13,2h 26m,Change begins with a whisper.,25000000,216639112,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
246,247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000,14480,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
247,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),Not Available,Not Available,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
248,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000,52767889,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
249,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000,424208848,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [3]:
df.head()

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose

In [4]:
df.head(3)

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"

In [5]:
df.tail()

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
245,246,The Help,2011,8.1,Drama,PG-13,2h 26m,Change begins with a whisper.,25000000,216639112,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
246,247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000,14480,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
247,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),Not Available,Not Available,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
248,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000,52767889,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
249,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000,424208848,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [6]:
df.sample(4)

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
135,136,Ran,1985,8.2,"Action,Drama,War",R,2h 42m,tionDramaWar,11500000,4164283,"Tatsuya Nakadai,Akira Terao,Jinpachi Nezu,Dais...",Akira Kurosawa,"Akira Kurosawa,Hideo Oguni,Masato Ide"
216,217,Stand by Me,1986,8.1,"Adventure,Drama",13+,1h 29m,"For some, it's the last real taste of innocenc...",8000000,52287414,"Wil Wheaton,River Phoenix,Corey Feldman,Jerry ...",Rob Reiner,"Stephen King,Raynold Gideon,Bruce A. Evans"
64,65,Aliens,1986,8.4,"Action,Adventure,Sci-Fi",R,2h 17m,This time there's more.,18500000,131060248,"Sigourney Weaver,Michael Biehn,Carrie Henn,Pau...",James Cameron,"James Cameron,David Giler,Walter Hill"

In [7]:
df[2:4]

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"

In [8]:
df.shape

(250, 13)

In [9]:
df["name"]

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3         The Godfather Part II
4                  12 Angry Men
                 ...
245                    The Help
246                 Dersu Uzala
247                     Aladdin
248                      Gandhi
249          Dances with Wolves
Name: name, Length: 250, dtype: object

In [10]:
df.rating

0      9.3
1      9.2
2      9.0
3      9.0
4      9.0
      ...
245    8.1
246    8.2
247    8.0
248    8.0
249    8.0
Name: rating, Length: 250, dtype: float64

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
type(df.rating)

pandas.core.series.Series

In [13]:
dir(df.rating)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [14]:
df.rating.min(), df.rating.max(), df.rating.mean()

(np.float64(8.0), np.float64(9.3), np.float64(8.3072))

In [15]:
df_Approved= df[df.certificate== "Approved"]
df_R= df[df.certificate== "R"]

In [16]:
df_Approved

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
9,10,"The Good, the Bad and the Ugly",1966,8.8,"Adventure,Western",Approved,2h 58m,They formed an alliance of hate to steal a for...,1200000,25253887,"Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo ...",Sergio Leone,"Luciano Vincenzoni,Sergio Leone,Agenore Incrocci"
59,60,Paths of Glory,1957,8.4,"Drama,War",Approved,1h 28m,Never has the screen thrust so deeply into the...,935000,5252,"Kirk Douglas,Ralph Meeker,Adolphe Menjou,Georg...",Stanley Kubrick,"Stanley Kubrick,Calder Willingham,Jim Thompson"
63,64,Witness for the Prosecution,1957,8.4,"Crime,Drama,Mystery",Approved,1h 56m,The most electrifying entertainment of our time!,3000000,7693,"Tyrone Power,Marlene Dietrich,Charles Laughton...",Billy Wilder,"Agatha Christie,Billy Wilder,Harry Kurnitz"
96,97,Lawrence of Arabia,1962,8.3,"Adventure,Biography,Drama",Approved,3h 38m,A Mighty Motion Picture Of Action And Adventure!,15000000,45720631,"Peter O'Toole,Alec Guinness,Anthony Quinn,Jack...",David Lean,"Robert Bolt,Michael Wilson"
97,98,North by Northwest,1959,8.3,"Action,Adventure,Mystery",Approved,2h 16m,Alfred Hitchcock takes you.... North by Northw...,3101000,142319,"Cary Grant,Eva Marie Saint,James Mason,Jessie ...",Alfred Hitchcock,Ernest Lehman
101,102,The Apartment,1960,8.3,"Comedy,Drama,Romance",Approved,2h 5m,"Movie-wise, there has never been anything like...",3000000,18778738,"Jack Lemmon,Shirley MacLaine,Fred MacMurray,Ra...",Billy Wilder,"Billy Wilder,I.A.L. Diamond"
109,110,To Kill a Mockingbird,1962,8.3,"Crime,Drama",Approved,2h 9m,The most beloved and widely read Pulitzer Priz...,2000000,599146,"Gregory Peck,John Megna,Frank Overton,Rosemary...",Robert Mulligan,"Harper Lee,Horton Foote"
133,134,Judgment at Nuremberg,1961,8.3,"Drama,War",Approved,2h 59m,More than a motion picture...It is an overwhel...,3000000,12180,"Spencer Tracy,Burt Lancaster,Richard Widmark,M...",Stanley Kramer,"Abby Mann,Montgomery Clift"
147,148,The Great Escape,1963,8.2,"Adventure,Drama,History",Approved,2h 52m,put a fence in front of these men...and they'l...,4000000,228178,"Steve McQueen,James Garner,Richard Attenboroug...",John Sturges,"Paul Brickhill,James Clavell,W.R. Burnett"
181,182,On the Waterfront,1954,8.1,"Crime,Drama,Thriller",Approved,1h 48m,The Man Lived by the Jungle Law of the Docks!,910000,910000 (estimated),"Marlon Brando,Karl Malden,Lee J. Cobb,Rod Stei...",Elia Kazan,"Budd Schulberg,Malcolm Johnson,Robert Siodmak"
187,188,The Third Man,1949,8.1,"Film-Noir,Mystery,Thriller",Approved,1h 33m,Carol Reed's Classic Thriller,Not Available,1226507,"Orson Welles,Joseph Cotten,Alida Valli,Trevor ...",Carol Reed,"Graham Greene,Orson Welles,Alexander Korda"
224,225,The Best Years of Our Lives,1946,8.1,"Drama,Romance,War",Approved,2h 50m,THE SCREEN'S GREATEST LOVE STORY IS THE BEST F...,2100000,23661347,"Myrna Loy,Dana Andrews,Fredric March,Teresa Wr...",William Wyler,"Robert E. Sherwood,MacKinlay Kantor"
236,237,Rebecca,1940,8.1,"Drama,Film-Noir,Mystery",Approved,2h 10m,THE MIGHTY NOVEL LEAPS TO TURBULENT LIFE ON TH...,1288000,72275,"Laurence Olivier,Joan Fontaine,George Sanders,...",Alfred Hitchcock,"Daphne Du Maurier,Robert E. Sherwood,Joan Harr..."

In [17]:
df_R

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
5,6,Schindler's List,1993,9.0,"Biography,Drama,History",R,3h 15m,"Whoever saves one life, saves the world entire.",22000000,322161245,"Liam Neeson,Ralph Fiennes,Ben Kingsley,Carolin...",Steven Spielberg,"Thomas Keneally,Steven Zaillian"
7,8,Pulp Fiction,1994,8.9,"Crime,Drama",R,2h 34m,Girls like me don't make invitations like this...,8000000,213928762,"John Travolta,Uma Thurman,Samuel L. Jackson,Br...",Quentin Tarantino,"Quentin Tarantino,Roger Avary"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,220,Into the Wild,2007,8.1,"Adventure,Biography,Drama",R,2h 28m,Into the heart Into the soul,15000000,56675895,"Emile Hirsch,Vince Vaughn,Catherine Keener,Mar...",Sean Penn,"Sean Penn,Jon Krakauer"
220,221,Before Sunset,2004,8.1,"Drama,Romance",R,1h 20m,What if you had a second chance with the one t...,Not Available,Not Available,"Ethan Hawke,Julie Delpy,Vernon Dobtcheff,Louis...",Richard Linklater,"Richard Linklater,Julie Delpy,Ethan Hawke"
225,226,The Exorcist,1973,8.1,Horror,R,2h 2m,The movie you've been waiting for...without th...,11000000,441306145,"Ellen Burstyn,Max von Sydow,Linda Blair,Lee J....",William Friedkin,William Peter Blatty
235,236,Amores Perros,2000,8.1,"Drama,Thriller",R,2h 34m,Love. Betrayal. Death.,2000000,20908467,"Emilio EchevarrÃ­a,Gael GarcÃ­a Bernal,Goya Tole...",Alejandro G. IÃ±Ã¡rritu,Guillermo Arriaga
243,244,Life of Brian,1979,8.0,Comedy,R,1h 34m,A motion picture destined to offend nearly two...,4000000,20745728,"Graham Chapman,John Cleese,Michael Palin,Terry...",Terry Jones,"Graham Chapman,John Cleese,Terry Gilliam"

In [18]:
float(df_Approved.rating.min()), float(df_Approved.rating.max()), float(df_Approved.rating.mean())

(8.1, 9.0, 8.335714285714285)

In [19]:
min_rating = float(df_R.rating.min())
max_rating = float(df_R.rating.max())
mean_rating = float(df_R.rating.mean())

print(min_rating, max_rating, mean_rating)

8.0 9.3 8.325773195876288